---
title: "Assignment1_submission"
author: "Muhammad Ahsan Asif"
date: "23/08/2019"
output: html_document
---
## Task 1
```{r}
library(tidyverse)

# TASK 1.1

# Importing the csv into a dataframe

gov_data <- read.csv('govhack3.csv')

# Checking the number of rows

nrow(gov_data)

#Checking the number of columns

ncol(gov_data)

```

## Task 2
## Task 2.1
```{r}
#TASK 2.1 Cleaning up columns

ed_data_link <- 'govhack3.csv'
top_row <- read_csv(ed_data_link, col_names = FALSE, n_max = 1)
second_row <- read_csv(ed_data_link, n_max = 1)

column_names <- second_row %>% 
  unlist(., use.names=FALSE) %>% 
  make.unique(., sep = "__") # double underscore

column_names[2:8] <- str_c(column_names[2:8], '0', sep='__')

daily_attendance <- 
  read_csv(ed_data_link, skip = 2, col_names = column_names)

#Extracting the names of the hospitals with na
HospitalNames = t(top_row) %>% na.omit()
view(HospitalNames)

```

## #Task 2.2 Tidying Data
```{r}
library(ggplot2)
library(lubridate)
New_Data <- daily_attendance %>% gather(key = "NewVariables", value = "NewValues", -Date )
New_Data <- New_Data %>% separate(NewVariables,into = c('Variables','Hospitals'),sep = "__")
New_Data <- New_Data %>% spread(key = 'Variables', value = 'NewValues' )

#Viewing the datatypes of all columns
str(New_Data)

#Changing their data types from char to Date and numeric
New_Data$Date <- dmy(New_Data$Date)
New_Data$Admissions <- as.numeric(New_Data$Admissions)
New_Data$Attendance <- as.numeric(New_Data$Attendance)
New_Data$Tri_1 <- as.numeric(New_Data$Tri_1)
New_Data$Tri_2 <- as.numeric(New_Data$Tri_2)
New_Data$Tri_3 <- as.numeric(New_Data$Tri_3)
New_Data$Tri_4 <- as.numeric(New_Data$Tri_4)
New_Data$Tri_5 <- as.numeric(New_Data$Tri_5)

#Viewwing the data after changing the variable types
str(New_Data)
# Replacing NA with 0
New_Data[is.na(New_Data)]=0
View(New_Data)

```


## Task 3
##Task 3.1
```{r}

#Task 3.1 Select a hospital

#Using filter to grab all the rows and column for Royal Perth Hospital from the Dataset
RoyalPerthHospital <- New_Data %>% filter(Hospitals == '0')

#Printing the name of the hospital 
print(HospitalNames[1])

#Printing the total number of ED attendances 
print(RoyalPerthHospital["Attendance"])

#Printing the total number of ED Admissions 
print(RoyalPerthHospital["Admissions"])

```

## Task 3.2

```{r}
#Before plotting i will arrange the column Date in an order 

RoyalPerthHospital <- RoyalPerthHospital %>% arrange(Date)

#Plotting The Royal Perth hospital 

ggplot(data = RoyalPerthHospital, aes(x=Date,y = Attendance)) + geom_point(color = "red") + geom_line(color = "Black")

```

## Task 3.3
```{r}
#Task 3.3

#PLotting for a week
WeeklyData = head(RoyalPerthHospital,7)
ggplot(data = WeeklyData, aes(x=Date,y = Attendance)) + geom_point(color = "red") + geom_line(color = "black")

```

## Task 3.4

```{r}
#Taking a random sample of 200 record from the Royal Perth Hospital 
RandomSample = RoyalPerthHospital %>% sample_n(200,replace = FALSE)
```

## Task 4
## Task 4.1
```{r}
library(fitdistrplus)
#Applying poisson distribution 
poissond <- RandomSample$Tri_2
poissondist <- dpois(x = poissond, lambda = 30)

#Plotting the poisson distribution across the random sample
plot(poissondist,col = "blue")
hist(poissondist,col = 'blue')


#Applying negative binomial distribution 
ndist <- fitdist(RandomSample$Tri_2,"nbinom")
nbinomdist <- dnbinom(RandomSample$Tri_2,size = 133.43123,mu = 35.82089)

#Plotting the poisson distribution across the random sample
plot(nbinomdist,col="red")
hist(nbinomdist,col = "red")


```

## Task 4.2
```{r}
#Comparing the log likelihood
summary(poissondist)
summary(nbinomdist)
```



